/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import static view.TelaInicial.Desktop;

/**
 *
 * @author Romerson
 */
public class ManterMoradorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManterMoradores
     */
    public ManterMoradorView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRemoverRepublica = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        btnConvidar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Manter Moradores da República");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Data de Ingresso", "Rateio %"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 461, 130));

        btnRemoverRepublica.setText("Remover da República");
        btnRemoverRepublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverRepublicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoverRepublica, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 220, 70, -1));

        btnHistorico.setText("Ver Histórico");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        btnConvidar.setText("Convidar Morador / Sem Teto");
        btnConvidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvidarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvidarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        EditarMoradorView a = new EditarMoradorView();
        Desktop.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverRepublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverRepublicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverRepublicaActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoricoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvidar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnRemoverRepublica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnConvidar() {
        return btnConvidar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnHistorico() {
        return btnHistorico;
    }

    public JButton getBtnRemoverRepublica() {
        return btnRemoverRepublica;
    }




}
