/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JMenuItem;

/**
 *
 * @author Romerson
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuManterRepublica = new javax.swing.JMenuItem();
        menuCriarRepublica = new javax.swing.JMenuItem();
        menuBuscarVagas = new javax.swing.JMenuItem();
        menuResultadoMensal = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuManterPerfil = new javax.swing.JMenuItem();
        menuAceitarConvite = new javax.swing.JMenuItem();
        menuManterMorador = new javax.swing.JMenuItem();
        menuConvidarMorador = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuManterTarefa = new javax.swing.JMenuItem();
        menuRegistrar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuManterReceita = new javax.swing.JMenuItem();
        menuFazerEstorno = new javax.swing.JMenuItem();
        menuConsultarReceita = new javax.swing.JMenuItem();
        menuRegistrarReceita = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuConfirmarReclamacao = new javax.swing.JMenuItem();
        menuManterReclamacao = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("República");

        menuManterRepublica.setText("Manter república");
        menuManterRepublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManterRepublicaActionPerformed(evt);
            }
        });
        jMenu1.add(menuManterRepublica);

        menuCriarRepublica.setText("Criar república");
        menuCriarRepublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCriarRepublicaActionPerformed(evt);
            }
        });
        jMenu1.add(menuCriarRepublica);

        menuBuscarVagas.setText("Buscar vagas");
        menuBuscarVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarVagasActionPerformed(evt);
            }
        });
        jMenu1.add(menuBuscarVagas);

        menuResultadoMensal.setText("Consultar resultado mensal");
        menuResultadoMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuResultadoMensalActionPerformed(evt);
            }
        });
        jMenu1.add(menuResultadoMensal);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Morador");

        menuManterPerfil.setText("Manter perfil");
        menuManterPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManterPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(menuManterPerfil);

        menuAceitarConvite.setText("Aceitar convite");
        menuAceitarConvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAceitarConviteActionPerformed(evt);
            }
        });
        jMenu2.add(menuAceitarConvite);

        menuManterMorador.setText("Manter moradores");
        menuManterMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManterMoradorActionPerformed(evt);
            }
        });
        jMenu2.add(menuManterMorador);

        menuConvidarMorador.setText("Convidar moradores/ Aceitar convite");
        menuConvidarMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConvidarMoradorActionPerformed(evt);
            }
        });
        jMenu2.add(menuConvidarMorador);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tarefas");

        menuManterTarefa.setText("Manter tarefas");
        menuManterTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManterTarefaActionPerformed(evt);
            }
        });
        jMenu3.add(menuManterTarefa);

        menuRegistrar.setText("Registrar conclusão da tarefa");
        menuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarActionPerformed(evt);
            }
        });
        jMenu3.add(menuRegistrar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Lançamentos");

        menuManterReceita.setText("Manter receitas e despesas");
        menuManterReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManterReceitaActionPerformed(evt);
            }
        });
        jMenu4.add(menuManterReceita);

        menuFazerEstorno.setText("Fazer estorno de lançamentos");
        menuFazerEstorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFazerEstornoActionPerformed(evt);
            }
        });
        jMenu4.add(menuFazerEstorno);

        menuConsultarReceita.setText("Consultar minhas receitas e despesas");
        menuConsultarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarReceitaActionPerformed(evt);
            }
        });
        jMenu4.add(menuConsultarReceita);

        menuRegistrarReceita.setText("Registrar pagamento de receita ou despesas");
        menuRegistrarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarReceitaActionPerformed(evt);
            }
        });
        jMenu4.add(menuRegistrarReceita);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Reclamações/Sugestões ");

        menuConfirmarReclamacao.setText("Confirmar solução de reclamações / sugestões");
        menuConfirmarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfirmarReclamacaoActionPerformed(evt);
            }
        });
        jMenu6.add(menuConfirmarReclamacao);

        menuManterReclamacao.setText("Manter reclamações / sugestões");
        menuManterReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManterReclamacaoActionPerformed(evt);
            }
        });
        jMenu6.add(menuManterReclamacao);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Sair");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu5.add(sair);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFazerEstornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFazerEstornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFazerEstornoActionPerformed

    private void menuManterRepublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManterRepublicaActionPerformed
       
    }//GEN-LAST:event_menuManterRepublicaActionPerformed

    private void menuManterTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManterTarefaActionPerformed
        
    }//GEN-LAST:event_menuManterTarefaActionPerformed

    private void menuCriarRepublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCriarRepublicaActionPerformed
        
    }//GEN-LAST:event_menuCriarRepublicaActionPerformed

    private void menuManterMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManterMoradorActionPerformed
       
    }//GEN-LAST:event_menuManterMoradorActionPerformed

    private void menuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarActionPerformed
        
    }//GEN-LAST:event_menuRegistrarActionPerformed

    private void menuManterReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManterReceitaActionPerformed
        
    }//GEN-LAST:event_menuManterReceitaActionPerformed

    private void menuConvidarMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConvidarMoradorActionPerformed
        
    }//GEN-LAST:event_menuConvidarMoradorActionPerformed

    private void menuConfirmarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfirmarReclamacaoActionPerformed
        
    }//GEN-LAST:event_menuConfirmarReclamacaoActionPerformed

    private void menuManterPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManterPerfilActionPerformed
        
    }//GEN-LAST:event_menuManterPerfilActionPerformed

    private void menuAceitarConviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAceitarConviteActionPerformed
       
    }//GEN-LAST:event_menuAceitarConviteActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    private void menuBuscarVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarVagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBuscarVagasActionPerformed

    private void menuResultadoMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuResultadoMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuResultadoMensalActionPerformed

    private void menuConsultarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultarReceitaActionPerformed

    private void menuRegistrarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRegistrarReceitaActionPerformed

    private void menuManterReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManterReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuManterReclamacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAceitarConvite;
    private javax.swing.JMenuItem menuBuscarVagas;
    private javax.swing.JMenuItem menuConfirmarReclamacao;
    private javax.swing.JMenuItem menuConsultarReceita;
    private javax.swing.JMenuItem menuConvidarMorador;
    private javax.swing.JMenuItem menuCriarRepublica;
    private javax.swing.JMenuItem menuFazerEstorno;
    private javax.swing.JMenuItem menuManterMorador;
    private javax.swing.JMenuItem menuManterPerfil;
    private javax.swing.JMenuItem menuManterReceita;
    private javax.swing.JMenuItem menuManterReclamacao;
    private javax.swing.JMenuItem menuManterRepublica;
    private javax.swing.JMenuItem menuManterTarefa;
    private javax.swing.JMenuItem menuRegistrar;
    private javax.swing.JMenuItem menuRegistrarReceita;
    private javax.swing.JMenuItem menuResultadoMensal;
    private javax.swing.JMenuItem sair;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getSair() {
        return sair;
    }

    public JMenuItem getMenuBuscarVagas() {
        return menuBuscarVagas;
    }

    public JMenuItem getMenuCriarRepublica() {
        return menuCriarRepublica;
    }

    public JMenuItem getMenuManterRepublica() {
        return menuManterRepublica;
    }

    public JMenuItem getMenuResultadoMensal() {
        return menuResultadoMensal;
    }

    public JMenuItem getMenuAceitarConvite() {
        return menuAceitarConvite;
    }

    public JMenuItem getMenuConvidarMorador() {
        return menuConvidarMorador;
    }

    public JMenuItem getMenuManterMorador() {
        return menuManterMorador;
    }

    public JMenuItem getMenuManterPerfil() {
        return menuManterPerfil;
    }

    public JMenuItem getMenuManterTarefa() {
        return menuManterTarefa;
    }

    public JMenuItem getMenuRegistrar() {
        return menuRegistrar;
    }

    public JMenuItem getMenuConsultarReceita() {
        return menuConsultarReceita;
    }

    public JMenuItem getMenuFazerEstorno() {
        return menuFazerEstorno;
    }

    public JMenuItem getMenuManterReceita() {
        return menuManterReceita;
    }

    public JMenuItem getMenuRegistrarReceita() {
        return menuRegistrarReceita;
    }

    public JMenuItem getMenuConfirmarReclamacao() {
        return menuConfirmarReclamacao;
    }

    public JMenuItem getMenuManterReclamacao() {
        return menuManterReclamacao;
    }
    
    

    
    
    

}
